MapeamentoEcossistema.WebUI/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MapeamentoEcossistema.WebUI.Models;

namespace MapeamentoEcossistema.WebUI.Controllers
{
    public class AccessController : Controller
    {
        // Fields.
        private readonly MapeamentoEntities _context;

        // Constructors.
        public AccessController(MapeamentoEntities context)
        {
            _context = context;
        }

        // Actions.
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string accessToken)
        {
            var user = _context.Users.FirstOrDefault(u => u.AccessToken == accessToken);

            if (user != null)
            {
                FormsAuthentication.SetAuthCookie(user.Id.ToString(), false);
                return RedirectToAction("Select");
            }
            else
            {
                ModelState.AddModelError("", "Código de acesso inválido.");
                return View();
            }
        }
        [Authorize]
        public ActionResult Select()
        {
            ViewBag.Id = new SelectList(_context.Questionnaires.OrderBy(q => q.Name), "Alias", "Name");
            return View();
        }
        [Authorize, HttpPost]
        public ActionResult Select(string id)
        {
            return RedirectToAction("Index", "Questionnaires", new { id = id });
        }
    }
}

MapeamentoEcossistema.WebUI/Views/Access/Index.cshtml
<body class="bg-1">
    <div class="geral">
        <section class="conteudo">
            <div class="row-max">
                <div class="main grid_6 offset_3">
                    @using (Html.BeginForm("Index", "Access", FormMethod.Post, new { @class = "nysmnyd-labels" }))
                    {
                        <h1>Questionário Ecossistema
                            <br>
                            Startups</h1>
                        
                        <div style="margin: 0 95px">
                            @Html.ValidationSummary(true)
                        </div>
                        
                        <fieldset class="campo-busca">
                            @Html.TextBox("accessToken", Request["accessToken"], new { id = "cod", placeholder = "Insira o Código Verificador" })
                            <small>Código Inválido</small>
                        </fieldset>

                        <fieldset class="bt-enviar">
                            <input type="submit" value="Entrar">
                        </fieldset>

                        @*<p>Insira o Código Verificador</p>*@
                    }
                </div>
            </div>

            <div class="row-max logo-container">
                <div class="grid_12">
                    <img src="/Content/img/logo-sebrae.png" alt="Sebrae">
                </div>
            </div>
        </section>
    </div>

    <script>$(':text').focus()</script>
</body>

MapeamentoEcossistema.WebUI/Views/Access/Select.cshtml
<body class="bg-2">
    <div class="geral">
        <section class="conteudo">
            <div class="row-max">
                <div class="main tela-2 grid_6 offset_3">
                    @using (Html.BeginForm("Select", "Access", FormMethod.Post, new { id = "myForm", @class = "nysmnyd-labels" }))
                    {
                        <h1>Questionário Ecossistema
                            <br>
                            Startups</h1>

                        if (TempData["SUCCESS_MESSAGE"] != null)
                        {
                            <div class="alert alert-success" style="margin: 0 94px">
                                @TempData["SUCCESS_MESSAGE"]
                            </div>
                        }
                        
                        <fieldset class="campo-regiao">
                            <label for="options">Selecione</label>
                            <span class="select">
                                @Html.DropDownList("Id", null, "Selecione o tipo do questionário", new { id = "ddl" })
                            </span>
                            <small>Invalid entry</small>
                        </fieldset>
                    }
                </div>
            </div>

            <div class="row-max logo-container tela-2">
                <div class="grid_6 offset_3">
                    <p>2014 - Desenvolvido por Sebrae. Todos os Direitos Reservados.</p>
                    <img src="/Content/img/logo-sebrae.png" alt="Sebrae">
                </div>
            </div>
        </section>
    </div>

    <script type="text/javascript">
        $('#ddl').change(function (e) { $('#myForm').submit() });
    </script>

</body>